### ISSUE TITLE
What is the lisense?

### ISSUE THREAD

**Issue by whatisgravity** [larsjsol/NavGrid#1]
I was going to start working on something very similar to this because the advanced tactics on the UE store is built only using blue prints and the creator is not interested in releasing it open source. I wanted to know what it is before I start work since it doesn't seem to be specified and there is no license file. 

Public domain? MIT? BSD? GPL?

**Comment by larsjsol** [comment]
LGPL 3. It is my understanding that this will allow you to dynamically link this with software that is not released under a GPL-compatible license (e.g. UE4), while also obligating you to make the source code for NavGrid available if you redistribute it.

As a side note: If your starting on a fresh project it might be worthwhile to take a look at the devel branch as the code there supports multilevel grids and rudimentary support for ladders. Unfortunately the documentation has not yet been brought up to date.

**Comment by whatisgravity** [comment]
Great, I plan to release all of my game open source anyways. I may just fork your project and work on it that way we can share advancements. Thanks for starting this.

**Comment by larsjsol** [comment]
I look forward to see how your games turn out.

Feel free to get in touch if you run into any issues when integrating this into your projects.
