### ISSUE TITLE
Integration problem

### ISSUE THREAD

**Issue by almas123** [larsjsol/NavGrid#2]
Hello, I cant understand .Do not display all classes when adding a plug-in "http://imgur.com/JJSBgoI" ,Could you please explain this point in detail. I would like to see more examples,Thank you for help

**Comment by larsjsol** [comment]
Hi

The could be caused by a few different things:
1. Did the plugin compile ok?
2. Did you enable the plugin in the Editor?

You should be able to find a line that says `NavGrid: Starting` in the output log when starting your project.

**Comment by almas123** [comment]
That's what I get ,http://imgur.com/a/GqL3D " was aborted." , UE4 4.16.1. VS 2015

**Comment by larsjsol** [comment]
Hm. I haven't seen that before... Is your project by any chance named "NavGrid"? 

Does the plugin compile ok? Can you find the plugin in the list of available plugins?

**Comment by almas123** [comment]
If I use a different project name, I get http://imgur.com/a/OmANM ,http://imgur.com/a/xkDkF
i see him in plugins http://imgur.com/a/rJi34

**Comment by larsjsol** [comment]
> i see him in plugins http://imgur.com/a/rJi34

Ok. This is a good sign

Is it possible for you to upload your project somewhere? That way I can take a look and see if I can figure out what's wrong

**Comment by almas123** [comment]
https://drive.google.com/open?id=0B_A2sl7_Ch9qN24zN3NSZXQ0aEk

**Comment by larsjsol** [comment]
Thanks.

I can find two things that might cause problems:
1. The code for the plugin should be placed in `<YourProject>/Plugins/NavGrid` in order for the build system to find the code. In the project you sendt me the code located directly under `<YourProject>/Plugins`

2. Your project is called `NavGrid`, which creates a namespace collision with the plugin. I would suggest that you start over in a new project with a different name.

Good luck!

**Comment by almas123** [comment]
Thanks  for the help
