### ISSUE TITLE
Video

### ISSUE THREAD

**Issue by RobertCoppert** [larsjsol/NavGrid#3]
Hi
I found your video example ,https://www.youtube.com/watch?v=FoqGXE3b7FE, Is it possible for you to upload your example somewhere?thanks.

**Comment by larsjsol** [comment]
I dont have that exact project anymore, but you can get a simple demo from https://drive.google.com/drive/u/0/folders/0Bxk7gYfi_5mPQ2FoR2EtMDVQSUE.

This does not include any animated character models as show in the video. You can easily add that yourself by extending the GridPawn class (either as a blueprint or in C++) and assigning a skeletal mesh with an AnimBP.

**Comment by RobertCoppert** [comment]
Thank you for example,How can I create another pawn class?
Something else besides ExampleGridPawn.
When I try to create, I get an .due to NAVGRID_API in my custom pawn class.
And I also did not find where ExampleGridPawn set Cone to static mesh.

**Comment by larsjsol** [comment]
> How can I create another pawn class?

I guess the easiest way would be to use the class wizard in the editor. Pick `New C++ Class` in the `File` menu and choose `GridPawn` as the base class. Or you can create a blueprint using GridPawn as the parent class.

But, you might also have found a bug. Would it be possible for you to get the latest source code (i.e git pull or re-download) and try again? If it still fails, it would be very useful if you could paste in the complete error message.

> And I also did not find where ExampleGridPawn set Cone to static mesh.

The mesh is set in the constructor for `AExampleGridPawn` (found in ExampleGridPawn.cpp):
```
// Fill out your copyright notice in the Description page of Project Settings.

#include "NavGridPrivatePCH.h"
#include "ExampleGridPawn.h"

#include "Components/StaticMeshComponent.h"
#include "Components/ArrowComponent.h"

AExampleGridPawn::AExampleGridPawn()
	:Super()
{
	StaticMesh = CreateDefaultSubobject<UStaticMeshComponent>("StaticMesh");
	UStaticMesh *Mesh = ConstructorHelpers::FObjectFinder<UStaticMesh>(TEXT("StaticMesh'/Engine/BasicShapes/Cone.Cone'")).Object;
	StaticMesh->SetStaticMesh(Mesh);
	StaticMesh->SetRelativeLocation(FVector(0, 0, 50));
	StaticMesh->SetupAttachment(Scene);

...
```

**Comment by RobertCoppert** [comment]
When I using GridPawn as the parent class.
Successfully added class 'MyGridPawn', however you must recompile the 'Project' module before it will appear in the Content Browser. Failed to automatically hot reload the 'Project' module.

Would you like to open the Output Log to see more details?

and OutPut Log
http://imgur.com/a/Owqci

**Comment by larsjsol** [comment]
Thanks!

> Successfully added class 'MyGridPawn', however you must recompile the 'Project' module before it will appear in the Content Browser. Failed to automatically hot reload the 'Project' module.

> Would you like to open the Output Log to see more details?

This is completely normal

> and OutPut Log
http://imgur.com/a/Owqci

That however, is not. I'm not sure what to make that to be honest.

Can you upload your project somewhere so I can take a look at it?

**Comment by RobertCoppert** [comment]
I found a problem, it was my missing, I apologize.
But can u tell me,how to package my project with your plugin?I got this error, http://imgur.com/a/x7tkY I think it's because of the plugin

**Comment by larsjsol** [comment]
Yeah. That might be the plugin. I'll look into it.

**Comment by larsjsol** [comment]
I've pushed some changes that should fix this.

You might need to clean or rebuild in Visual Studio before packaging from the editor.

**Comment by RobertCoppert** [comment]
Now it works for windows!
But there are still problems with mobile platforms.
The build issue starts after adding "NavGrid" in .Build.cs file.

**Comment by larsjsol** [comment]
The latest commit should fix it for android.

I have not tested on IOS. To be honest, when I look at the docs getting started with IOS is seems like more effort than I am willing to put in for a platform I am not targeting myself. I can take a quick look at it if you give me the complete error message.

**Comment by RobertCoppert** [comment]
UATHelper: Packaging (iOS): Running AutomationTool...
UATHelper: Packaging (iOS): Automation.ParseCommandLine: Parsing command line: -ScriptsForProject=D:/UE4/Pile_of_Ash/Pile_of_Ash.uproject BuildCookRun -nocompile -nocompileeditor -installed -nop4 -project=D:/UE4/Pile_of_Ash/Pile_of_Ash.uproject -cook -stage -archive -archivedirectory=C:/Users/almas/Desktop -package -clientconfig=DebugGame -ue4exe=UE4Editor-C
md.exe -pak -prereqs -nodebuginfo -targetplatform=IOS -build -utf8output
UATHelper: Packaging (iOS): BuildCookRun.SetupParams: Setting up ProjectParams for D:\UE4\Pile_of_Ash\Pile_of_Ash.uproject
UATHelper: Packaging (iOS): Project.Build: ********** BUILD COMMAND STARTED **********
UATHelper: Packaging (iOS): CommandUtils.Run: Run: D:\UE4\UE_4.16\Engine\Binaries\DotNET\UnrealBuildTool.exe Pile_of_Ash IOS DebugGame -Project=D:\UE4\Pile_of_Ash\Pile_of_Ash.uproject  D:\UE4\Pile_of_Ash\Pile_of_Ash.uproject -NoUBTMakefiles  -remoteini="D:\UE4\Pile_of_Ash" -noxge -generatemanifest -NoHotReload
UATHelper: Packaging (iOS): UnrealBuildTool: Picking the default remote server Pile_of_Ash
UATHelper: Packaging (iOS): UnrealBuildTool: Remote compiling requires Delta Copy to be installed. Use the editor (Project Settings, IOS) to set up your remote compilation settings.
UATHelper: Packaging (iOS): CommandUtils.Run: Run: Took 1.625084s to run UnrealBuildTool.exe, ExitCode=0
UATHelper: Packaging (iOS): CommandUtils.Run: Run: D:\UE4\UE_4.16\Engine\Binaries\DotNET\UnrealBuildTool.exe Pile_of_Ash IOS DebugGame -Project=D:\UE4\Pile_of_Ash\Pile_of_Ash.uproject  D:\UE4\Pile_of_Ash\Pile_of_Ash.uproject -NoUBTMakefiles  -remoteini="D:\UE4\Pile_of_Ash" -noxge -NoHotReload -ignorejunk
UATHelper: Packaging (iOS): UnrealBuildTool: Picking the default remote server Pile_of_Ash
UATHelper: Packaging (iOS): UnrealBuildTool: Remote compiling requires Delta Copy to be installed. Use the editor (Project Settings, IOS) to set up your remote compilation settings.
UATHelper: Packaging (iOS): UnrealBuildTool: Doing xcode-select --print-path
UATHelper: Packaging (iOS): UnrealBuildTool: ERROR: Failed to start local process for action ("The system cannot find the file specified"): D:/UE4/Pile_of_Ash/Content\ssh.exe -o BatchMode=yes  Batman_Pile@Pile_of_Ash "cd \"/\" && xcode-select --print-path"
UATHelper: Packaging (iOS): CommandUtils.Run: Run: Took 44.4236335s to run UnrealBuildTool.exe, ExitCode=5
UATHelper: Packaging (iOS): Program.Main: ERROR: AutomationTool terminated with exception: AutomationTool.CommandUtils+CommandFailedException: Command failed (Result:5): D:\UE4\UE_4.16\Engine\Binaries\DotNET\UnrealBuildTool.exe Pile_of_Ash IOS DebugGame -Project=D:\UE4\Pile_of_Ash\Pile_of_Ash.uproject  D:\UE4\Pile_of_Ash\Pile_of_Ash.uproject -NoUBTMakefiles 
 -remoteini="D:\UE4\Pile_of_Ash" -noxge -NoHotReload -ignorejunk. See logfile for details: 'UnrealBuildTool-2017.07.08-05.50.34.txt' 
UATHelper: Packaging (iOS):    at AutomationTool.CommandUtils.RunAndLog(String App, String CommandLine, String Logfile, Int32 MaxSuccessCode, String Input, ERunOptions Options, Dictionary`2 EnvVars, SpewFilterCallbackType SpewFilterCallback) in D:\UE4\UE_4.16\Engine\Source\Programs\AutomationTool\AutomationUtils\ProcessUtils.cs:line 913
UATHelper: Packaging (iOS):    at AutomationTool.CommandUtils.RunAndLog(CommandEnvironment Env, String App, String CommandLine, String LogName, Int32 MaxSuccessCode, String Input, ERunOptions Options, Dictionary`2 EnvVars, SpewFilterCallbackType SpewFilterCallback) in D:\UE4\UE_4.16\Engine\Source\Programs\AutomationTool\AutomationUtils\ProcessUtils.cs:line 8
66
UATHelper: Packaging (iOS):    at AutomationTool.CommandUtils.RunUBT(CommandEnvironment Env, String UBTExecutable, String CommandLine, String LogName, Dictionary`2 EnvVars) in D:\UE4\UE_4.16\Engine\Source\Programs\AutomationTool\AutomationUtils\UBTUtils.cs:line 51
UATHelper: Packaging (iOS):    at AutomationTool.CommandUtils.RunUBT(CommandEnvironment Env, String UBTExecutable, FileReference Project, String Target, String Platform, String Config, String AdditionalArgs, String LogName, Dictionary`2 EnvVars) in D:\UE4\UE_4.16\Engine\Source\Programs\AutomationTool\AutomationUtils\UBTUtils.cs:line 89
UATHelper: Packaging (iOS):    at AutomationTool.UE4Build.BuildWithUBT(String TargetName, UnrealTargetPlatform TargetPlatform, String Config, FileReference UprojectPath, Boolean ForceMonolithic, Boolean ForceNonUnity, Boolean ForceDebugInfo, Boolean ForceFlushMac, Boolean DisableXGE, String InAddArgs, Boolean ForceUnity, Dictionary`2 EnvVars) in D:\UE4\UE_4.
16\Engine\Source\Programs\AutomationTool\AutomationUtils\UE4Build.cs:line 373
UATHelper: Packaging (iOS):    at AutomationTool.UE4Build.Build(BuildAgenda Agenda, Nullable`1 InDeleteBuildProducts, Boolean InUpdateVersionFiles, Boolean InForceNoXGE, Boolean InUseParallelExecutor, Boolean InForceNonUnity, Boolean InForceUnity, Boolean InShowProgress, Dictionary`2 PlatformEnvVars, Nullable`1 InChangelistNumberOverride, Dictionary`2 InTarg
etToManifest) in D:\UE4\UE_4.16\Engine\Source\Programs\AutomationTool\AutomationUtils\UE4Build.cs:line 1485
UATHelper: Packaging (iOS):    at Project.Build(BuildCommand Command, ProjectParams Params, Int32 WorkingCL, ProjectBuildTargets TargetMask) in D:\UE4\UE_4.16\Engine\Source\Programs\AutomationTool\Scripts\BuildProjectCommand.Automation.cs:line 192
UATHelper: Packaging (iOS):    at BuildCookRun.DoBuildCookRun(ProjectParams Params) in D:\UE4\UE_4.16\Engine\Source\Programs\AutomationTool\Scripts\BuildCookRun.Automation.cs:line 207
UATHelper: Packaging (iOS):    at BuildCookRun.ExecuteBuild() in D:\UE4\UE_4.16\Engine\Source\Programs\AutomationTool\Scripts\BuildCookRun.Automation.cs:line 40
UATHelper: Packaging (iOS):    at AutomationTool.BuildCommand.Execute() in D:\UE4\UE_4.16\Engine\Source\Programs\AutomationTool\AutomationUtils\BuildCommand.cs:line 100
UATHelper: Packaging (iOS):    at AutomationTool.Automation.Execute(List`1 CommandsToExecute, CaselessDictionary`1 Commands) in D:\UE4\UE_4.16\Engine\Source\Programs\AutomationTool\AutomationUtils\Automation.cs:line 566
UATHelper: Packaging (iOS):    at AutomationTool.Automation.Process(String[] Arguments) in D:\UE4\UE_4.16\Engine\Source\Programs\AutomationTool\AutomationUtils\Automation.cs:line 536
UATHelper: Packaging (iOS):    at AutomationTool.Program.MainProc(Object Param) in D:\UE4\UE_4.16\Engine\Source\Programs\AutomationTool\Program.cs:line 133
UATHelper: Packaging (iOS):    at AutomationTool.InternalUtils.RunSingleInstance(Func`2 Main, Object Param) in D:\UE4\UE_4.16\Engine\Source\Programs\AutomationTool\AutomationUtils\Utils.cs:line 704
UATHelper: Packaging (iOS):    at AutomationTool.Program.Main() in D:\UE4\UE_4.16\Engine\Source\Programs\AutomationTool\Program.cs:line 57
UATHelper: Packaging (iOS): Program.Main: AutomationTool exiting with ExitCode=5 (5)
UATHelper: Packaging (iOS): BUILD FAILED
PackagingResults:Error: Error Unknown Error


Remote build errors,I can give you  later with MAC., But I do not think that it will be different.



Android fixed , thank you

**Comment by RobertCoppert** [comment]
Maybe, You must be tired of me,  I am sorry but i found one more problem,The Touch event does not work for
"TileActor"when u touch.Only click even.

**Comment by larsjsol** [comment]
>Maybe, You must be tired of me

I'm not. You have discovered several bugs and I appreciate that you tell me about them :)

 >The Touch event does not work for "TileActor"when u touch.

Yeah. That makes sense as I have not implemented touch events. I should be fairly easy to add though. I will look into it.

> Only click even.

I'm sorry, but I do not understand this. Does that mean that clicking works for you or not?

**Comment by larsjsol** [comment]
I've just pushed a commit with support for touch events. I hope it works for you.

About IOS support. Do you have the chance to make a new attempt at packaging for IOS and sending me the build tool log (located at `%USERPROFILE%\AppData\Roaming\Unreal Engine\AutomationTool\Logs\UnrealBuildTool-YYYY.MM.DD-HH.mm.ss.txt`)?
