### ISSUE TITLE
v2.2.2. Pawn is not activating

### ISSUE THREAD

**Issue by Miru302** [larsjsol/NavGrid#5]
I've posted the issue on the plugin thread as well.
https://forums.unrealengine.com/community/community-content-tools-and-tutorials/62299-navgrid-turn-based-navigation-on-a-grid

2.2.0 version works fine. But in 2.2.2 Pawn is not getting SelectedHighlight turned on (visual indication that class is not recognized by NavGrid?) and doesn't interact in anyway.

**Comment by Miru302** [comment]
I've been stupid and cloned master brunch directly. Tried release version 2.2.2 and it works fine. Sorry~

**Comment by larsjsol** [comment]
Hm. While the releases are usually a safer bet, the master branch should work. 

It does work in my current project, but it does not when I create a new project and then add the plugin. I'll look into this.

**Comment by larsjsol** [comment]
I'm pretty sure this works in master now.
