### ISSUE TITLE
Linking errors when creating empty class derived from GridPawn

### ISSUE THREAD

**Issue by DrScientific** [larsjsol/NavGrid#7]
Hi!  
  
I'm attempting to make a class derived from GridPawn.  
```c
#pragma once

#include "CoreMinimal.h"
#include "Classes/GridPawn.h"
#include "DSExampleGridPawn.generated.h"

UCLASS()
class DRAGONSPINE_API ADSExampleGridPawn : public AGridPawn
{
	GENERATED_BODY()

public:	
	
};
```
Whenever I attempt to compile however I'm getting these linking errors which seem to imply the GetTeamAttitudeTowards function in `UE_4.19\Engine\Source\Runtime\AIModule\ClassesGenericTeamAgentInterface.h`  
 of the Engine is undefined.  
  
`DSExampleGridPawn.cpp.obj : error LNK2001: unresolved external symbol "public: virtual enum ETeamAttitude::Type __cdecl IGenericTeamAgentInterface::GetTeamAttitudeTowards(class AActor const &)const " (?GetTeamAttitudeTowards@IGenericTeamAgentInterface@@UEBA?AW4Type@ETeamAttitude@@AEBVAActor@@@Z)
DSExampleGridPawn.gen.cpp.obj : error LNK2001: unresolved external symbol "public: virtual enum ETeamAttitude::Type __cdecl IGenericTeamAgentInterface::GetTeamAttitudeTowards(class AActor const &)const " (?GetTeamAttitudeTowards@IGenericTeamAgentInterface@@UEBA?AW4Type@ETeamAttitude@@AEBVAActor@@@Z)`  
  
Which it is of course. I've been trying to figure out why this might be happening all day, but haven't really been able to find anything substantial. You wouldn't happen to have ant idea why this might be happening would you? Thanks for your time and sorry to bother you.

**Comment by larsjsol** [comment]
Hi

Hm. It seems like your project does not link properly with the AIModule... This could very well be a bug in my code. I'll try to look into it later today.

You might be able to get around this by adding AIModule to `PublicDependencyModuleNames` in `<yourproject>.Build.cs` and the rebuilding your project.

**Comment by larsjsol** [comment]
> You might be able to get around this by adding AIModule to PublicDependencyModuleNames in <yourproject>.Build.cs and the rebuilding your project.

Actually, this is the only way I know of that fixes this :) Feel free to get in touch if this for some reason does not work for you.

**Comment by DrScientific** [comment]
Awesome, that works perfectly! Thanks so much for the help!

**Comment by DrScientific** [comment]
Why exactly did that work actually? I would have thought including the AIModule would have been covered through inclusion of the Engine.
